-- MySQL Script generated by MySQL Workbench
-- Thu Jan 11 00:30:54 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema clinica_unifranz_reservas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema clinica_unifranz_reservas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `clinica_unifranz_reservas` DEFAULT CHARACTER SET utf8 ;
USE `clinica_unifranz_reservas` ;

-- -----------------------------------------------------
-- Table `clinica_unifranz_reservas`.`servicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinica_unifranz_reservas`.`servicios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre_servicio` VARCHAR(80) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinica_unifranz_reservas`.`estado_civil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinica_unifranz_reservas`.`estado_civil` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(80) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinica_unifranz_reservas`.`genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinica_unifranz_reservas`.`genero` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(80) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinica_unifranz_reservas`.`reserva_consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinica_unifranz_reservas`.`reserva_consulta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(80) NOT NULL,
  `apat` VARCHAR(80) NOT NULL,
  `amat` VARCHAR(80) NOT NULL,
  `direccion` VARCHAR(80) NULL,
  `correo` VARCHAR(80) NULL,
  `telefono` INT NOT NULL,
  `celular` INT NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `dni` VARCHAR(10) NOT NULL,
  `fecha_creacion` DATETIME NULL,
  `fecha_actualizacion` DATETIME NULL,
  `atendido` TINYINT(1) NULL DEFAULT 0,
  `estado_civil_id` INT NOT NULL,
  `genero_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_reserva_cita_estado_civil_idx` (`estado_civil_id` ASC),
  INDEX `fk_reserva_cita_genero1_idx` (`genero_id` ASC),
  CONSTRAINT `fk_reserva_cita_estado_civil`
    FOREIGN KEY (`estado_civil_id`)
    REFERENCES `clinica_unifranz_reservas`.`estado_civil` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_reserva_cita_genero1`
    FOREIGN KEY (`genero_id`)
    REFERENCES `clinica_unifranz_reservas`.`genero` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinica_unifranz_reservas`.`consulta_tiene_servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinica_unifranz_reservas`.`consulta_tiene_servicio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `reserva_consulta_id` INT NOT NULL,
  `servicios_id` INT NOT NULL,
  `fecha_creacion` DATETIME NULL,
  `fecha_actualizacion` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_consulta_tiene_servicio_reserva_consulta1_idx` (`reserva_consulta_id` ASC),
  INDEX `fk_consulta_tiene_servicio_servicios1_idx` (`servicios_id` ASC),
  CONSTRAINT `fk_consulta_tiene_servicio_reserva_consulta1`
    FOREIGN KEY (`reserva_consulta_id`)
    REFERENCES `clinica_unifranz_reservas`.`reserva_consulta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_consulta_tiene_servicio_servicios1`
    FOREIGN KEY (`servicios_id`)
    REFERENCES `clinica_unifranz_reservas`.`servicios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinica_unifranz_reservas`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinica_unifranz_reservas`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre_usuario` VARCHAR(80) NOT NULL,
  `password` VARCHAR(80) NOT NULL,
  `fecha_creacion` DATETIME NULL,
  `fecha_actualizacion` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
