-- INSERTAR TODOS LOS SERVICIOS --
INSERT INTO servicios(nombre_servicio) VALUES('ACUPUNTURA');
INSERT INTO servicios(nombre_servicio) VALUES('CIRUJIA ESTÉTICA');
INSERT INTO servicios(nombre_servicio) VALUES('CIRUJIA GENERAL');
INSERT INTO servicios(nombre_servicio) VALUES('DERMATOLOGÍA');
INSERT INTO servicios(nombre_servicio) VALUES('FISIOTERAPIA');
INSERT INTO servicios(nombre_servicio) VALUES('GINECOLOGÍA');
INSERT INTO servicios(nombre_servicio) VALUES('MEDICINA INTERNA');
INSERT INTO servicios(nombre_servicio) VALUES('NEUROLOGÍA');
INSERT INTO servicios(nombre_servicio) VALUES('OFTALMOLOGÍA');
INSERT INTO servicios(nombre_servicio) VALUES('OTORRINOLARINGOLOGÍA');
INSERT INTO servicios(nombre_servicio) VALUES('PEDIATRÍA');
INSERT INTO servicios(nombre_servicio) VALUES('TRAUMATOLOGÍA');
INSERT INTO servicios(nombre_servicio) VALUES('UROLOGÍA');
INSERT INTO servicios(nombre_servicio) VALUES('CARDIOLOGÍA');
INSERT INTO servicios(nombre_servicio) VALUES('PSICOLOGÍA');
INSERT INTO servicios(nombre_servicio) VALUES('CURACIONES DE QUEMADURAS');
INSERT INTO servicios(nombre_servicio) VALUES('CURACIONES EN CONSULTORIO');
INSERT INTO servicios(nombre_servicio) VALUES('INYECTABLE');
INSERT INTO servicios(nombre_servicio) VALUES('NEBULIZACIÓN');
INSERT INTO servicios(nombre_servicio) VALUES('RETIROS DE PUNTOS');
INSERT INTO servicios(nombre_servicio) VALUES('SERVICIO OXÍGENO');
INSERT INTO servicios(nombre_servicio) VALUES('SUTURAS');
INSERT INTO servicios(nombre_servicio) VALUES('TIRA REACTIVA');
INSERT INTO servicios(nombre_servicio) VALUES('TOMA PRESIÓN ARTERIAL');
INSERT INTO servicios(nombre_servicio) VALUES('VENOCLISIS');
INSERT INTO servicios(nombre_servicio) VALUES('AFILIACIÓN PLAN DE SALUD');
INSERT INTO servicios(nombre_servicio) VALUES('ELECTROENCEFALOGRAMA');
INSERT INTO servicios(nombre_servicio) VALUES('OZONOTERAPIA');
INSERT INTO servicios(nombre_servicio) VALUES('SALA DE RECUPERACIÓN');
INSERT INTO servicios(nombre_servicio) VALUES('SERVICIOS DE AMBULANCIA');
INSERT INTO servicios(nombre_servicio) VALUES('USO DE CONSULTORIO');
INSERT INTO servicios(nombre_servicio) VALUES('ACUPUNTURA');
INSERT INTO servicios(nombre_servicio) VALUES('DETECCIÓN DE ENFERMEDADES DE LA PROSTATA');
INSERT INTO servicios(nombre_servicio) VALUES('DETECCIÓN DE ENFERMEDADES DE LOS RIÑONES');
INSERT INTO servicios(nombre_servicio) VALUES('DETECCIÓN DE HERNIAS');
INSERT INTO servicios(nombre_servicio) VALUES('ENFERMEDADES GASTROINTESTINALES Y VESICULAR BILIAR');
